services:
  web:
    build: .
    volumes:
      - ./php_app:/var/www/html
    ports:
      - "80:80"
    environment:
      POSTGRES_DB: ctf
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: example
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ctf
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
